### ISSUE TITLE
Associated types fail to compile

### ISSUE THREAD

**Issue by austinjones** [audunhalland/unimock#17]
Hi @audunhalland!  I ran into a bug where generated unimock code won't compile on traits with associated types.  Here is the code:

```
#[unimock::unimock]
pub trait Client {
    type DatabaseImpl: Database;

    fn database(&self, name: &str) -> Self::DatabaseImpl;
}

#[unimock::unimock]
pub trait Database {}
```

There are two issues in the generated code:

1)
```
type Response = ::unimock::output::Owned<Self::DatabaseImpl>;

associated type `DatabaseImpl` not found for `Self`
there is a similarly named associated type `DatabaseImpl` in the trait `MongoClient`
```
This one can be fixed by rewriting as: `<::unimock::Unimock as Client>::DatabaseImpl`

2)
```
impl MongoClient for ::unimock::Unimock {
    fn database(...) { ... }
}
not all trait items implemented, missing: `DatabaseImpl`
missing `DatabaseImpl` in implementation
```
In this case, it can be fixed by setting `type DatabaseImpl = Self`, which uses the impl generated in the macro invocation on `trait Database`.

**Comment by audunhalland** [comment]
Unimock explicitly [does not support associated types](https://docs.rs/unimock/0.4.9/unimock/index.html#what-kinds-of-traits-or-methods-cannot-be-mocked). I don't see how it would make sense to have a "mock implementation" of such traits.

Note that you can also manually implement the trait for Unimock instead of using the macro.

**Comment by austinjones** [comment]
Yeah, that makes sense... it's not always clear how to bind the associated types.  Sometimes it's `Unimock`, or `String`, or `()`.

I'll close this issue.  Thanks for looking at it!

**Comment by audunhalland** [comment]
Version 0.5 now lets you specify associated types in the macro invocation.
