### ISSUE TITLE
`.returns` parameter should not have to implement Clone if quantification is `Once`

### ISSUE THREAD

**Issue by audunhalland** [audunhalland/unimock#4]
This is solvable, but requires a refactoring of the public types inside `build`. What needs to be done is that the type returned from `.returns()` has to be 100% strongly typed, and only type-erased in the next quantification step.

**Comment by canac** [comment]
Looking forward to this landing! Right now, I can't mock functions returning `anyhow::Result` because `Result` don't implement `Clone`. And unfortunately, most of the functions in my program return results.

**Comment by audunhalland** [comment]
For now (0.3.x) it's possible to use `.answers(|_| Ok(..))`  instead of `.returns(..)`. This is already implemented in the 0.4-alpha versions (the `next` branch), but I'm looking at some other potential improvements before 0.4 gets released.

**Comment by audunhalland** [comment]
Version `0.4.0` which fixes this issue has been released. Whenever a method is mocked using `.some_call` or `.next_call`, (which kind of implies that it should be called one time) there is no `Clone` bound on the return value.

Will soon release a new version of `entrait` with support for the new unimock version.
